USE master
GO

-- SET TRANSACTION ISOLATION LEVEL
--     { READ UNCOMMITTED
--     | READ COMMITTED
--     | REPEATABLE READ
--     | SNAPSHOT
--     | SERIALIZABLE
--     }

ALTER DATABASE [DEMO] SET READ_COMMITTED_SNAPSHOT OFF;
GO