USE DEMO;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION;
INSERT INTO dbo.Wishlist VALUES (1, 5);
WAITFOR DELAY '00:00:20';
COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION;
DELETE FROM dbo.Wishlist WHERE PersonId = 1 and StuffId = 5
WAITFOR DELAY '00:00:50';
COMMIT TRANSACTION;
