USE DEMO;

--DROP PARTITION SCHEME PS5000;
--DROP PARTITION FUNCTION PFDEMO;

CREATE PARTITION FUNCTION PFdemo (int)  
AS RANGE LEFT FOR VALUES (1, 5000, 10000, 15000);  
-- TODO: Left vs Right

CREATE PARTITION SCHEME PS5000
AS PARTITION PFdemo  
TO (test1fg, test2fg, test3fg, test4fg, test5fg);

--Add partition to table
ALTER TABLE dbo.IndexTest ADD CONSTRAINT [PK_IndexTest_id] PRIMARY KEY CLUSTERED 
([id] ASC)
WITH
(	PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, --SORT_IN_TEMPDB = OFF,
	IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON
)
ON [PS5000] (id)
