USE DEMO;

--Displays the number of milliseconds required to parse, compile, and execute each statement
SET STATISTICS TIME ON;
--Displays information about the amount of disk activity generated by Transact-SQL statements
SET STATISTICS IO ON;

SELECT *
FROM dbo.Employee;

SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;

--*OUTPUT:
--*SQL Server Execution Times:
--*    CPU time = 0 ms, elapsed time = 0 ms. 

--*(6 rows affected) 
--*Table 'Employee'. Scan count 1, logical reads 2, physical reads 0, page server reads 0, read-ahead reads 0, 
--* page server read-ahead reads 0, lob logical reads 0, lob physical reads 0, lob page server reads 0, 
--* lob read-ahead reads 0, lob page server read-ahead reads 0. 

--*SQL Server Execution Times:
--*    CPU time = 0 ms, elapsed time = 0 ms. 
